apiVersion : apps/v1
kind: Deployment
metadata:
  name: genmockdatabackend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genmockdatabackend
  template:
    metadata:
      labels:
        app: genmockdatabackend 
    spec:
      containers:
        - name: genmockdatabackend 
          image: genmockdata.azurecr.io/genmockdatabackend
          ports:
          - containerPort: 8080